package org.ipan.nrgyrent.telegram;

public enum States {
    START,
    MAIN_MENU,
    DEPOSIT,
    WALLETS,
    HISTORY,

    USER_PROMPT_WITHDRAW_BALANCE_TYPE,
    USER_PROMPT_WITHDRAW_AMOUNT,
    USER_PROMPT_WITHDRAW_WALLET,

    NEW_WALLET_PROMPT_ADDRESS,
    NEW_WALLET_PROMPT_LABEL,
    ADD_WALLETS_SUCCESS,
    DELETE_WALLETS_SUCCESS,
    USER_WALLET_PREVIEW,

    TRANSACTION_PROMPT_WALLET,
    TRANSACTION_PROMPT_BALANCE_TYPE,
    TRANSACTION_65k,
    TRANSACTION_131k,
    TRANSACTION_CUSTOM_AMOUNT_65k,
    TRANSACTION_SUCCESS,
    TRANSACTION_PENDING,
    TRANSACTION_ERROR,

    MANAGER_GROUP_PREVIEW,
    MANAGER_GROUP_VIEW_USERS,
    MANAGER_GROUPS_ACTION_ADD_USERS,
    MANAGER_GROUPS_ACTION_ADD_USERS_SUCCESS,
    MANAGER_GROUPS_ACTION_REMOVE_USERS,
    MANAGER_GROUPS_ACTION_REMOVE_USERS_SUCCESS,


    // admin
    ADMIN_MENU,
    ADMIN_MANAGE_TARIFFS,
    ADMIN_MANAGE_GROUPS,
    ADMIN_MANAGE_USERS,
    ADMIN_VIEW_ITRX_BALANCE,
    ADMIN_VIEW_SWEEP_BALANCE,

    ADMIN_VIEW_PROMPT_WITHDRAW_WALLET,
    ADMIN_VIEW_PROMPT_WITHDRAW_AMOUNT,


    ADMIN_MANAGE_USERS_ACTION_PREVIEW,
    ADMIN_MANAGE_USER_ACTION_PROMPT_NEW_BALANCE,
    ADMIN_MANAGE_USER_ACTION_DEACTIVATE_CONFIRM,
    ADMIN_MANAGE_USER_ACTION_DEACTIVATE_SUCCESS,
    ADMIN_MANAGE_USER_ACTION_CHANGE_TARIFF_SEARCHING,
    ADMIN_MANAGE_USER_ACTION_CHANGE_TARIFF_SUCCESS,



    ADMIN_MANAGE_GROUPS_ACTION_PREVIEW,
    ADMIN_MANAGE_GROUPS_ACTION_USERS_REVIEW,
    ADMIN_MANAGE_GROUPS_ACTION_ADD_USERS,
    ADMIN_MANAGE_GROUPS_ACTION_ADD_USERS_SUCCESS,
    ADMIN_MANAGE_GROUPS_ACTION_REMOVE_USERS,
    ADMIN_MANAGE_GROUPS_ACTION_REMOVE_USERS_SUCCESS,
    ADMIN_MANAGE_GROUPS_ACTION_CHANGE_TARIFF_SUCCESS,
    ADMIN_MANAGE_GROUPS_ACTION_CHANGE_TARIFF_SEARCHING,

    ADMIN_MANAGE_GROUPS_ACTION_PROMPT_NEW_MANAGER,
    ADMIN_MANAGE_GROUPS_ACTION_MANAGER_CHANGED_SUCCESS,


    ADMIN_MANAGE_GROUPS_ACTION_PROMPT_NEW_BALANCE,
    ADMIN_MANAGE_GROUPS_ACTION_BALANCE_ADJUSTED_SUCCESS,

    ADMIN_MANAGE_GROUPS_ACTION_PROMPT_NEW_LABEL,
    ADMIN_MANAGE_GROUPS_ACTION_RENAMED_SUCCESS,

    ADMIN_MANAGE_GROUPS_ACTION_DEACTIVATE_CONFIRM,
    ADMIN_MANAGE_GROUPS_ACTION_DEACTIVATE_SUCCESS,


    ADMIN_MANAGE_GROUPS_SEARCH,

    ADMIN_MANAGE_GROUPS_ADD_PROMPT_LABEL,
    ADMIN_MANAGE_GROUPS_ADD_PROMPT_MANAGER,

    ADMIN_MANAGE_GROUPS_REMOVE_PROMPT_USERS,
    ADMIN_MANAGE_GROUPS_ADD_SUCCESS,


    // Tariffs management
    ADMIN_MANAGE_TARIFFS_SEARCH,
    ADMIN_MANAGE_TARIFFS_ADD_PROMPT_LABEL,
    ADMIN_MANAGE_TARIFF_ADD_PROMPT_TX1_AMOUNT,
    ADMIN_MANAGE_TARIFF_ADD_PROMPT_TX2_AMOUNT,
    ADMIN_MANAGE_TARIFFS_ADD_SUCCESS,

    ADMIN_MANAGE_TARIFF_ACTION_PREVIEW,
    ADMIN_MANAGE_TARIFF_ACTION_DEACTIVATE_SUCCESS,
    ADMIN_MANAGE_TARIFF_ACTION_DEACTIVATE_CONFIRM,
    ADMIN_MANAGE_TARIFF_ACTION_RENAMED_SUCCESS,

    ADMIN_MANAGE_TARIFF_ACTION_PROMPT_NEW_LABEL,
    ADMIN_MANAGE_TARIFF_ACTION_PROMPT_TX1_AMOUNT,
    ADMIN_MANAGE_TARIFF_ACTION_PROMPT_TX2_AMOUNT,
    ADMIN_MANAGE_TARIFF_ACTION_CHANGE_AMOUNT_SUCCESS,
    ADMIN_MANAGE_TARIFF_ACTION_ADD_SUCCESS,

}
