package org.ipan.nrgyrent.telegram;

public enum States {
    START,
    CHOOSE_LANGUAGE,
    MAIN_MENU,
    SETTINGS,
    SETTINGS_CHANGE_LANGUAGE,
    DEPOSIT,
    WALLETS,
    HISTORY,
    REFERALS,
    AUTOTOPUP,

    AUTODELEGATE_START_ERROR,

    USER_PROMPT_WITHDRAW_BALANCE_TYPE,
    USER_PROMPT_WITHDRAW_AMOUNT,
    USER_PROMPT_WITHDRAW_WALLET,

    AUTO_TOPUP_NEW_WALLET_PROMPT_ADDRESS,
    AUTO_TOPUP_NEW_WALLET_PROMPT_LABEL,
    AUTO_TOPUP_NEW_WALLET_PROMPT_SUCCESS,

    NEW_WALLET_PROMPT_ADDRESS,
    NEW_WALLET_PROMPT_LABEL,
    ADD_WALLETS_SUCCESS,
    DELETE_WALLETS_SUCCESS,
    USER_WALLET_PREVIEW,

    TRANSACTION_PROMPT_WALLET,
    TRANSACTION_65k,
    TRANSACTION_131k,
    TRANSACTION_CUSTOM_AMOUNT_65k,
    TRANSACTION_PENDING,
    TRANSACTION_SUCCESS,
    TRANSACTION_ERROR,

    MANAGER_GROUP_PREVIEW,
    MANAGER_GROUP_VIEW_USERS,
    MANAGER_GROUPS_ACTION_ADD_USERS,
    MANAGER_GROUPS_ACTION_ADD_USERS_SUCCESS,
    MANAGER_GROUPS_ACTION_REMOVE_USERS,
    MANAGER_GROUPS_ACTION_REMOVE_USERS_SUCCESS,


    // admin
    ADMIN_MENU,
    ADMIN_MANAGE_TARIFFS,
    ADMIN_MANAGE_REF_PROGRAMS,
    ADMIN_MANAGE_GROUPS,
    ADMIN_MANAGE_USERS,
    ADMIN_VIEW_ITRX_BALANCE,
    ADMIN_VIEW_CURRENT_ENERGY_PROVIDER,
    ADMIN_VIEW_SWEEP_BALANCE,

    ADMIN_VIEW_PROMPT_WITHDRAW_WALLET,
    ADMIN_VIEW_PROMPT_WITHDRAW_AMOUNT,


    ADMIN_MANAGE_USERS_ACTION_PREVIEW,
    ADMIN_MANAGE_USER_ACTION_PROMPT_NEW_BALANCE,
    ADMIN_MANAGE_USER_ACTION_DEACTIVATE_CONFIRM,
    ADMIN_MANAGE_USER_ACTION_DEACTIVATE_SUCCESS,

    // Changing user tariff
    ADMIN_MANAGE_USER_ACTION_CHANGE_TARIFF_SEARCHING,
    ADMIN_MANAGE_USER_ACTION_CHANGE_TARIFF_SUCCESS,

    // Changing user ref program
    ADMIN_MANAGE_USER_ACTION_CHANGE_REF_PROGRAM_SEARCHING,
    ADMIN_MANAGE_USER_ACTION_CHANGE_REF_PROGRAM_SUCCESS,


    ADMIN_MANAGE_GROUPS_ACTION_PREVIEW,
    ADMIN_MANAGE_GROUPS_ACTION_USERS_REVIEW,
    ADMIN_MANAGE_GROUPS_ACTION_ADD_USERS,
    ADMIN_MANAGE_GROUPS_ACTION_ADD_USERS_SUCCESS,
    ADMIN_MANAGE_GROUPS_ACTION_REMOVE_USERS,
    ADMIN_MANAGE_GROUPS_ACTION_REMOVE_USERS_SUCCESS,
    ADMIN_MANAGE_GROUPS_ACTION_CHANGE_TARIFF_SUCCESS,
    ADMIN_MANAGE_GROUPS_ACTION_CHANGE_TARIFF_SEARCHING,

    ADMIN_MANAGE_GROUPS_ACTION_PROMPT_NEW_MANAGER,
    ADMIN_MANAGE_GROUPS_ACTION_MANAGER_CHANGED_SUCCESS,


    ADMIN_MANAGE_GROUPS_ACTION_PROMPT_NEW_BALANCE,
    ADMIN_MANAGE_GROUPS_ACTION_BALANCE_ADJUSTED_SUCCESS,

    ADMIN_MANAGE_GROUPS_ACTION_PROMPT_NEW_LABEL,
    ADMIN_MANAGE_GROUPS_ACTION_RENAMED_SUCCESS,

    ADMIN_MANAGE_GROUPS_ACTION_DEACTIVATE_CONFIRM,
    ADMIN_MANAGE_GROUPS_ACTION_DEACTIVATE_SUCCESS,


    ADMIN_MANAGE_GROUPS_SEARCH,

    ADMIN_MANAGE_GROUPS_ADD_PROMPT_LABEL,
    ADMIN_MANAGE_GROUPS_ADD_PROMPT_MANAGER,

    ADMIN_MANAGE_GROUPS_REMOVE_PROMPT_USERS,
    ADMIN_MANAGE_GROUPS_ADD_SUCCESS,


    // Tariffs management
    ADMIN_MANAGE_TARIFFS_SEARCH,
    ADMIN_MANAGE_TARIFFS_ADD_PROMPT_LABEL,
    ADMIN_MANAGE_TARIFF_ADD_PROMPT_TX1_AMOUNT,
    ADMIN_MANAGE_TARIFF_ADD_PROMPT_TX2_AMOUNT,
    ADMIN_MANAGE_TARIFFS_ADD_SUCCESS,

    ADMIN_MANAGE_TARIFF_ACTION_PREVIEW,
    ADMIN_MANAGE_TARIFF_ACTION_DEACTIVATE_SUCCESS,
    ADMIN_MANAGE_TARIFF_ACTION_DEACTIVATE_CONFIRM,
    ADMIN_MANAGE_TARIFF_ACTION_RENAMED_SUCCESS,

    ADMIN_MANAGE_TARIFF_ACTION_PROMPT_NEW_LABEL,
    ADMIN_MANAGE_TARIFF_ACTION_PROMPT_TX1_AMOUNT,
    ADMIN_MANAGE_TARIFF_ACTION_PROMPT_TX2_AMOUNT,
    ADMIN_MANAGE_TARIFF_ACTION_CHANGE_AMOUNT_SUCCESS,
    ADMIN_MANAGE_TARIFF_ACTION_ADD_SUCCESS,

    // referral programs management
    ADMIN_MANAGE_REF_PROGRAMS_SEARCH,
    ADMIN_MANAGE_REF_PROGRAMS_ADD_PROMPT_LABEL,
    ADMIN_MANAGE_REF_PROGRAM_ADD_PROMPT_PERCENTAGE,
    ADMIN_MANAGE_REF_PROGRAMS_ADD_SUCCESS,

    ADMIN_MANAGE_REF_PROGRAM_ACTION_PREVIEW,
    ADMIN_MANAGE_REF_PROGRAM_ACTION_DEACTIVATE_SUCCESS,
    ADMIN_MANAGE_REF_PROGRAM_ACTION_DEACTIVATE_CONFIRM,
    ADMIN_MANAGE_REF_PROGRAM_ACTION_RENAMED_SUCCESS,

    ADMIN_MANAGE_REF_PROGRAM_ACTION_PROMPT_NEW_LABEL,
    ADMIN_MANAGE_REF_PROGRAM_ACTION_PROMPT_PERCENTAGE,


    ADMIN_MANAGE_REF_PROGRAM_ACTION_CHANGE_BASE_SUCCESS,

    ADMIN_MANAGE_REF_PROGRAM_ACTION_CHANGE_BASE_TX1,
    ADMIN_MANAGE_REF_PROGRAM_ACTION_CHANGE_BASE_TX2,
    ADMIN_MANAGE_REF_PROGRAM_ACTION_CHANGE_BASE_TX1_AUTO,
    ADMIN_MANAGE_REF_PROGRAM_ACTION_CHANGE_BASE_TX2_AUTO,

    ADMIN_MANAGE_REF_PROGRAM_ACTION_CHANGE_AMOUNT_SUCCESS,
    ADMIN_MANAGE_REF_PROGRAM_ACTION_ADD_SUCCESS,
    ADMIN_MANAGE_GROUPS_ACTION_PROMPT_NEW_WITHDRAW_LIMIT,
    ADMIN_MANAGE_GROUPS_ACTION_WITHDRAW_LIMIT_ADJUSTED_SUCCESS, ADMIN_MANAGE_USER_ACTION_PROMPT_WITHDRAW_LIMIT,
}
