/**
 * Nrgyrent Dashboard API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * One AML check. Financial values are decimal TRX.
 */
export interface AmlCheckRow { 
    id: number;
    date: string;
    nickname: string | null;
    name: string | null;
    balanceType: string;
    provider: string | null;
    tariff: string | null;
    walletToCheck: string | null;
    /**
     * AML check amount in decimal TRX.
     */
    amount: number;
    /**
     * AML check profit in decimal TRX.
     */
    profit: number;
    /**
     * AML check commission in decimal TRX.
     */
    commission: number;
    status: string;
    internalStatus: string;
    orderNumber: string | null;
}

