/**
 * Nrgyrent Dashboard API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AmlCheckRow } from './aml-check-row.model';


export interface AmlCheckPage { 
    content: Array<AmlCheckRow>;
    page: number;
    size: number;
    totalElements: number;
    totalPages: number;
}

