/**
 * Nrgyrent Dashboard API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrderRow } from './order-row.model';


export interface OrderPage { 
    content: Array<OrderRow>;
    page: number;
    size: number;
    totalElements: number;
    totalPages: number;
}

