/**
 * Nrgyrent Dashboard API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * One row of the Orders report. Financial fields are decimal TRX.
 */
export interface OrderRow { 
    id: number;
    date: string;
    login: string | null;
    name: string | null;
    balanceType: string;
    transactionsCount: number;
    totalEnergy: number;
    tariff: string | null;
    provider: string | null;
    /**
     * Commission in decimal TRX.
     */
    commission: number;
    /**
     * Income in decimal TRX.
     */
    income: number;
    /**
     * Referral deductions in decimal TRX.
     */
    referralDeductions: number;
    /**
     * Referral deduction remainder in decimal TRX.
     */
    referralDeductionsRemainder: number;
    /**
     * Profit in decimal TRX.
     */
    profit: number;
    walletActivated: boolean;
    status: string;
    recipient: string | null;
    orderNumber: string | null;
    transaction: string | null;
}

