/**
 * Nrgyrent Dashboard API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * One referral program payment. Amount is decimal TRX.
 */
export interface ReferralProgramPaymentRow { 
    user: string | null;
    /**
     * Payment amount in decimal TRX.
     */
    amount: number;
    date: string;
}

