/**
 * Nrgyrent Dashboard API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * One row of the Referral System report. Payment amounts are decimal TRX.
 */
export interface ReferralSystemRow { 
    referrer: string | null;
    referral: string | null;
    program: string | null;
    /**
     * Pending payment in decimal TRX.
     */
    pendingPayment: number;
    /**
     * Amount paid for the selected period in decimal TRX.
     */
    paidForPeriod: number;
    /**
     * Total amount paid in decimal TRX.
     */
    paidTotal: number;
}

