/**
 * Nrgyrent Dashboard API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReferralSystemRow } from './referral-system-row.model';


export interface ReferralSystemPage { 
    content: Array<ReferralSystemRow>;
    page: number;
    size: number;
    totalElements: number;
    totalPages: number;
}

