/**
 * Nrgyrent Dashboard API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReferralProgramPaymentRow } from './referral-program-payment-row.model';


export interface ReferralProgramPaymentPage { 
    content: Array<ReferralProgramPaymentRow>;
    page: number;
    size: number;
    totalElements: number;
    totalPages: number;
}

