/**
 * Nrgyrent Dashboard API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserWithdrawalRow } from './user-withdrawal-row.model';


export interface UserWithdrawalPage { 
    content: Array<UserWithdrawalRow>;
    page: number;
    size: number;
    totalElements: number;
    totalPages: number;
}

