/**
 * Nrgyrent Dashboard API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * One row of the User Profit report. Financial fields are decimal TRX.
 */
export interface UserProfitRow { 
    joinedAt: string | null;
    referral: string | null;
    balanceType: string;
    groupLogin: string | null;
    name: string | null;
    /**
     * Profit in decimal TRX.
     */
    profit: number;
    tariff: string | null;
    /**
     * Available balance in decimal TRX.
     */
    availableBalance: number;
    /**
     * Income in decimal TRX.
     */
    income: number;
    /**
     * ITRX commission in decimal TRX.
     */
    itrxCommission: number;
    /**
     * Referral deductions in decimal TRX.
     */
    referralDeductions: number;
    /**
     * Manual balance adjustments in decimal TRX.
     */
    manualAdjustments: number;
}

