/**
 * Nrgyrent Dashboard API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserProfitRow } from './user-profit-row.model';


export interface UserProfitPage { 
    content: Array<UserProfitRow>;
    page: number;
    size: number;
    totalElements: number;
    totalPages: number;
}

