/**
 * Nrgyrent Dashboard API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * One user withdrawal. Amount and commission are decimal TRX.
 */
export interface UserWithdrawalRow { 
    id: number;
    date: string;
    nickname: string | null;
    name: string | null;
    balanceType: string;
    /**
     * Withdrawal amount in decimal TRX.
     */
    amount: number;
    /**
     * Withdrawal commission in decimal TRX.
     */
    commission: number;
    status: string;
    recipient: string | null;
    transaction: string | null;
}

