package org.ipan.nrgyrent.domain.model;

public enum DepositStatus {
    USDT_ACKNOWLEDGED,
    USDT_ENERGY_RENTED,
    USDT_ENERGY_RENT_FAILED,

    USDT_TRANSFERRED_TO_BYBIT,
    USDT_TRANSFERRED_TO_BYBIT_FAILED,

    COMPLETED,
    USDT_MOVED_TO_UTA,
    USDT_MOVED_TO_UTA_FAILED,
    USDT_MARKET_ORDER_PLACED,
    USDT_MARKET_ORDER_PLACED_FAILED,
    USDT_MARKET_ORDER_UNEXPECTED_STATUS,
    USDT_ORDER_COMPLETED,
}
