// Generates src/environments/version.ts with build metadata.
// Invoked from Maven as: npm run generate-version <version> <output-file> <git-hash>
import { mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';

const args = process.argv.slice(2);
const [version = '0.0.0-dev', outputFile = 'src/environments/version.ts', gitHash = 'unknown'] = args;

const target = path.resolve(process.cwd(), outputFile);
mkdirSync(path.dirname(target), { recursive: true });

const content = [
  '// Generated by scripts/generate-version.mjs at build time. Do not edit manually.',
  `export const version = '${version}';`,
  `export const gitHash = '${gitHash}';`,
  `export const buildTime = '${new Date().toISOString()}';`,
  '',
].join('\n');

writeFileSync(target, content, 'utf8');
console.log(`[generate-version] wrote ${target}`);
