export * from './deposits.service';
import { DepositsService } from './deposits.service';
export * from './deposits.serviceInterface';
export * from './filters.service';
import { FiltersService } from './filters.service';
export * from './filters.serviceInterface';
export * from './general-statistics.service';
import { GeneralStatisticsService } from './general-statistics.service';
export * from './general-statistics.serviceInterface';
export * from './orders.service';
import { OrdersService } from './orders.service';
export * from './orders.serviceInterface';
export * from './user-profit.service';
import { UserProfitService } from './user-profit.service';
export * from './user-profit.serviceInterface';
export const APIS = [DepositsService, FiltersService, GeneralStatisticsService, OrdersService, UserProfitService];
