export * from './deposits.service';
import { DepositsService } from './deposits.service';
export * from './deposits.serviceInterface';
export * from './filters.service';
import { FiltersService } from './filters.service';
export * from './filters.serviceInterface';
export * from './general-statistics.service';
import { GeneralStatisticsService } from './general-statistics.service';
export * from './general-statistics.serviceInterface';
export * from './orders.service';
import { OrdersService } from './orders.service';
export * from './orders.serviceInterface';
export * from './referral-program-payments.service';
import { ReferralProgramPaymentsService } from './referral-program-payments.service';
export * from './referral-program-payments.serviceInterface';
export * from './referral-system.service';
import { ReferralSystemService } from './referral-system.service';
export * from './referral-system.serviceInterface';
export * from './user-profit.service';
import { UserProfitService } from './user-profit.service';
export * from './user-profit.serviceInterface';
export const APIS = [DepositsService, FiltersService, GeneralStatisticsService, OrdersService, ReferralProgramPaymentsService, ReferralSystemService, UserProfitService];
