/**
 * Nrgyrent Dashboard API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiError } from '../model/models';
import { FilterOption } from '../model/models';


import { NrgyrentDashboardConfiguration }                                     from '../configuration';



export interface FiltersServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: NrgyrentDashboardConfiguration;

    /**
     * List groups available to the dashboard filter
     * 
     * @endpoint get /api/v1/dashboard/filters/groups
     */
    getFilterGroups(extraHttpRequestParams?: any): Observable<Array<FilterOption>>;

    /**
     * List users available to the dashboard filter
     * 
     * @endpoint get /api/v1/dashboard/filters/users
     */
    getFilterUsers(extraHttpRequestParams?: any): Observable<Array<FilterOption>>;

}
