/**
 * Nrgyrent Dashboard API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiError } from '../model/models';
import { GeneralStatistics } from '../model/models';


import { NrgyrentDashboardConfiguration }                                     from '../configuration';



export interface GeneralStatisticsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: NrgyrentDashboardConfiguration;

    /**
     * Return dashboard-wide financial statistics
     * 
     * @endpoint get /api/v1/dashboard/general-statistics
     * @param userId Optional user filter.
     * @param groupId Optional group filter. Combined with userId using intersection semantics.
     * @param dateFrom Inclusive start date.
     * @param dateTo Inclusive end date.
     */
    getGeneralStatistics(userId?: number, groupId?: number, dateFrom?: string, dateTo?: string, extraHttpRequestParams?: any): Observable<GeneralStatistics>;

}
