/**
 * Nrgyrent Dashboard API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiError } from '../model/models';
import { UserWithdrawalPage } from '../model/models';


import { NrgyrentDashboardConfiguration }                                     from '../configuration';



export interface UserWithdrawalsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: NrgyrentDashboardConfiguration;

    /**
     * Return one page of user withdrawals
     * 
     * @endpoint get /api/v1/dashboard/user-withdrawals
     * @param page Zero-based page index.
     * @param size Requested number of rows per page.
     * @param userId Optional user filter.
     * @param groupId Optional group filter. Combined with userId using intersection semantics.
     * @param dateFrom Inclusive start date.
     * @param dateTo Inclusive end date.
     */
    getUserWithdrawals(page?: number, size?: number, userId?: number, groupId?: number, dateFrom?: string, dateTo?: string, extraHttpRequestParams?: any): Observable<UserWithdrawalPage>;

}
